### ISSUE TITLE
Track navigation (feature request)

### ISSUE THREAD

**Issue by FunkyBrewster** [chandler-stimson/audio-player#1]
I really appreciate this Chrome extension for use in remote teaching over Google Meet when I need to play audio clips clearly.
It would be even better if:
1) You could view the current playlist, and click tracks to skip to them (perhaps with a button like the similar Media Player extension).
2) You could skip back to the beginning of the current track. This is the expected behavior of the |< button, but it goes straight to the previous track. As it is, you have to drag on the navigation bar, which is not actually that easy to do.
Thanks.

**Comment by chandler-stimson** [comment]
The next release (0.2.4) has a built-in playlist. Increase the height of the player to see it. Also, you can use Ctrl + Shift + B to start the current track over.
